name: build-android-test-apk

on:
  workflow_dispatch:

env:
  NODE_VERSION: 20.13.1
  TERM: xterm

jobs:
  build-android-apk:
    runs-on: ubuntu-22.04
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@v4

      - name: ci/prepare-android-build
        uses: ./.github/actions/prepare-android-build
        with:
          sign: false
        env:
          STORE_FILE: "${{ secrets.MM_MOBILE_STORE_FILE }}"
          STORE_ALIAS: "${{ secrets.MM_MOBILE_STORE_ALIAS }}"
          STORE_PASSWORD: "${{ secrets.MM_MOBILE_STORE_PASSWORD }}"
          MATTERMOST_BUILD_GH_TOKEN: "${{ secrets.MATTERMOST_BUILD_GH_TOKEN }}"

      - name: Build Android APK
        run: |
          bundle exec fastlane android build --env android.release
        working-directory: ./fastlane

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-test-build-${{ github.run_id }}
          path: "*.apk"
