name: simple-android-build

on:
  workflow_dispatch:

env:
  NODE_VERSION: 20.13.1
  TERM: xterm

jobs:
  build-android:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configure Git
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "CI"

      - name: Install dependencies (skip solidarity)
        run: |
          npm install --ignore-scripts
          cd android && ./gradlew clean

      - name: Adjust Android SDK and Suppress Warnings
        run: |
          sed -i 's/compileSdkVersion [0-9]\+/compileSdkVersion 34/' android/app/build.gradle
          echo "android.suppressUnsupportedCompileSdk=35" >> android/gradle.properties
          sed -i 's/targetSdkVersion [0-9]\+/targetSdkVersion 34/' node_modules/@voximplant/react-native-foreground-service/android/build.gradle

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: android/app/build/outputs/apk/release/*.apk
